scripts/model_deploy.ipynb

#20 모델 배포 스크립트 작성

---

models/ryugibo_simple_model.ipynb

#20 seq_length 정보도 저장

---

scripts/model_deploy.ipynb

#20 배포 스크립트 정리

---

streamlit/base_model.py

#20 캐시 폴더 생성시 cwd추가

---

streamlit/base_model.py

#20 .cache 폴더를 생성하고 버전폴더를 생성하게 수정

---

streamlit/Home.py

#20 모델 반복해서 초기화하는 문제 수정

---

app/.gitignore
app/app/inference_model.py
app/app/ryugibo.py
app/app/state.py

#35 인퍼런스 모델 적용

---

models/1_empathy_only_BERT.ipynb

empathy데이터만 다시 돌림 (통합데이터 모델 돌린 후 정확도가 낮아서 공감만 다시 돌려보는 모델)

#5 empathy_only_bert

---

app/app/app_state.py
app/app/component/chat_history.py
app/app/component/navbar.py
app/app/page/dashboard.py
app/app/state/chat_state.py
app/app/state/login_state.py

cached_var에 저장된 한가지를 재사용.
그래도 여러번 쿼리하는 경우가 있어서, 추가 최적화 중

#68 DB 쿼리 호출 수 최적화 1차 

---

app/deploy/build.sh

#40 build 스크립트에서 requirements 설치 제거

---

app/.gitignore
app/app/page/dashboard.py
app/app/state/chat_state.py

- 대화 새로 시작 시 멈춰 보이는 부분 개선
- DB 인메모리 캐시 테스트

#68 하루 n개 대화 처리할 수 있도록 쿼리 추가

---

app/app/component/navbar.py
app/app/page/analysis.py
app/app/page/login.py
app/app/state/analysis_state.py

1. Pal-ette에서 iNotePal로 변경함 (navbar)
2. analysis page:  날짜 선택 중 종료일이 시작일보다 앞서지 않도록 체크
3. 차트 구현 (레이더차트, funnel chart, bar, line)

#64 analysis-graphs

---

app/app/component/navbar.py
app/app/page/calendar.py
app/app/state/calendar_state.py

calender.py, calender_state.py 주석 추가

#122 코드 주석 추가

---

app/app/component/navbar.py
app/app/page/calendar.py
app/app/state/calendar_state.py

날짜 선택 시 날짜 표시 안됨
날짜 선택 시 해당 날짜 채팅으로 넘어가지지 않음
-> 날짜만 선택됨

#122 네이게이션 바에 달력 추가

---

app/app/page/analysis.py
app/app/state/analysis_state.py
app/app/state/chat_state.py

radar chart: 전체 기간 데이터 추가 연동
bar, line: db데이터 연결

64 analysis without button

---

app/app/component/chat_input.py
app/app/component/emotion_card.py
app/app/component/navbar.py
app/app/page/analysis.py
app/app/page/dashboard.py
app/app/page/login.py
app/app/page/oauth.py
app/app/page/registration.py
app/app/page/word_cloud.py
app/requirements.txt

#197 
rx.chakra를 reflex_chakra를 사용하도록 수정

#197 rx.chakra deprecated 처리

---

app/app/component/navbar.py
app/app/page/analysis.py
app/app/page/dashboard.py
app/app/state/analysis_state.py
app/app/state/calendar_state.py
app/app/state/chat_state.py

달력 선택 날짜를 외부 스테이트의 변수를 참조시킬수 있도록 수정

#182 날짜 선택 최적화

---

app/alembic.ini
app/alembic/README
app/alembic/env.py
app/alembic/script.py.mako
app/app/__init__.py
app/app/db/__init__.py

#211 DB 초기화

---

app/rxconfig.py

#211 개발환경에서 reflex db migrate시 postgresql로 동작하는 문제 수정

---

app/app/page/login.py

#220 login 화면 chakra 제거중

---

app/app/page/registration.py
app/requirements.txt

#220 reflex 0.6.1 적용, registration 페이지 chakra 제거

---

app/app/component/navbar.py

#220 사이드 바 배경, 타이틀 정상화

---

app/app/page/login.py

#220 github로그인시 에러 발생하는 부분 수정

---

app/app/page/dashboard.py
app/app/state/chat_state.py

#220 감정 결과 팝업 지연 개선

---

app/app/__init__.py
app/app/app.py
app/app/component/navbar.py
app/app/page/__init__.py
app/app/page/analysis.py
app/app/page/dashboard.py
app/app/page/login.py
app/app/page/oauth.py
app/app/page/registration.py
app/app/page/reset_password.py
app/app/page/word_cloud.py

#220 
add_page 대신 rx.page 사용하도록 수정

#220 page 구조 rx.page로 변경

---

app/app/state/analysis_state.py

#220 통계화면 문자열로 날짜 계산하던 로직 수정

---

app/app/page/login.py
app/app/state/login_state.py

#220 로그인 버튼 오동작 수정

---

app/app/page/registration.py

#220 가입화면 접근 안되는 문제 수정

---

app/app/component/emotion_card.py
app/app/page/analysis.py
app/app/state/analysis_state.py
app/app/util/emotion.py

#220 감정상태 색상 맵을 공통 변수로 빼냄

---

app/app/state/analysis_state.py

#220 통계화면 기간 초기값 및 로직 수정
- 최근 30일간의 통계를 기본 기간으로 선택
- 사용하지 않는 graph_valid_check 제거
- 잘못된 범위를 선택했을 떄 팝업만 노출하고 화면 리셋하지 않음

#220 통계화면 기간 초기값 및 로직 수정

---

app/app/util/emotion.py

#220 개발환경 무작위 감정 선택 코드 수정

---

app/app/state/analysis_state.py

#220 중복 코드 보완

---

app/app/component/navbar.py
app/app/page/analysis.py
app/app/page/dashboard.py
app/app/state/calendar_state.py
app/app/state/chat_state.py

#220 달력 월 전환시 달력 갱신되지 않는 문제 수정

---

app/app/page/analysis.py
app/app/state/analysis_state.py
app/app/state/calendar_state.py

#220 통계화면 UI 정리

---

app/app/page/analysis.py
app/app/state/analysis_state.py

#220 통계화면 달력에 오늘로 이동하는 버튼 추가

---

app/requirements.txt
app/requirements_ubuntu.txt

#220 reflex 0.6.4 적용

---

app/rxconfig.py

#260 reflex 옵션으로 dotenv를 사용하도록 수정

---

app/app/component/navbar.py
app/app/page/analysis.py
app/app/page/dashboard.py
app/app/state/calendar_state.py
app/app/state/chat_state.py

#259 월 선택 기능

---

app/app/state/calendar_state.py

#259 월 부분 클릭됨을 알 수 있도록 변경

---

app/app/component/navbar.py
app/app/page/analysis.py
app/app/page/dashboard.py
app/app/state/calendar_state.py
app/app/state/chat_state.py

#259 년도 입력, 버그 수정

---

app/app/component/navbar.py
app/app/page/analysis.py
app/app/state/calendar_state.py

#220 오늘 버튼 정상화

---

app/app/component/emotion_card.py

#220 감정상태 표시 로직 정리

---

app/app/page/dashboard.py

#220 닫힌 대화를 계속 진행할 수 있는 문제 수정

---

app/app/component/chat_history.py

#220 다크모드일 때 말풍선 색 조정

---

app/app/state/chat_state.py

#220 대화 마칠 때 기존 대화정보가 아닌 새로운 대화 정보가 누적되는 문제 수정

---

app/app/state/calendar_state.py

#220 달력 년도 선택 화살표 정렬

---

app/app/page/dashboard.py
app/app/state/calendar_state.py
app/app/state/chat_state.py

#220 대화 기록 레이아웃 정리

---

app/app/state/calendar_state.py

#288 달력에 특정 날짜에 표시하는 기능 추가

---

app/app/state/login_state.py

iat 시간 보다 빠르게 로그인이 처리되는 경우가 있음..

#265 가끔 로그인 안돼는 문제 수정

---

app/app/state/chat_state.py

#251 처음 인삿말에 대화기록을 RAG에 넣어서 다채롭게 만들기

---

app/app/component/navbar.py
app/app/page/dashboard.py
app/app/state/calendar_state.py

#363 일부 나열된 스타일 tailwind 적용
